name: Microservice Sample

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: End-to-End Testing
        run: docker-compose run redise2etest
